### PR TITLE
prevent overflow on 32_bit platforms

### PR DESCRIPTION
**Pull request by CjiW**

### CODE REVIEW

**Comment by Chronostasys** [comment]
A bit more context.

The original code would fail the compilation on 32-bit platforms due to this overflow issue.  

[example ci](https://github.com/Pivot-Studio/pivot-lang/actions/runs/10108881443/job/27955664913)

**Comment by orxfun** [comment]
Thanks a lot for the fix! I am on vacation for a couple of weeks but will check and merge the branch as soon as I return.

**Comment by MichaReiser** [comment]
I tried the fix and it gets the project to compile but it seems there's an immediate runtime overflow in

```
    #[inline(always)]
    fn new_fragment_capacity_from(
        &self,
        fragment_capacities: impl ExactSizeIterator<Item = usize>,
    ) -> usize {
        fragment_capacities.last().map(|x| x * 2).unwrap_or(4)
    }
```

In `orx-split-vec-69c925888591bba4/24b4fda/src/growth/doubling/doubling_growth.rs:68:44`:

**Comment by orxfun** [comment]
@CjiW  and @Chronostasys . Thanks again for the issue and proposed fix. Only one note. The `CUMULATIVE_CAPACITIES` array must contain nonzero usizes. Could you consider the following minor refactoring on your fix:

```rust
pub(super) const FIRST_FRAGMENT_CAPACITY_POW: usize = 2;

pub(super) const FIRST_FRAGMENT_CAPACITY: usize = usize::pow(2, FIRST_FRAGMENT_CAPACITY_POW as u32);
pub(super) const SIZE_USIZE: usize = std::mem::size_of::<usize>() * 8;
pub(super) const OFFSET_FRAGMENT_IDX: usize = SIZE_USIZE - FIRST_FRAGMENT_CAPACITY_POW - 1;

const fn cumulative_capacity(fragment_idx: usize) -> usize {
    usize::pow(2, (fragment_idx + FIRST_FRAGMENT_CAPACITY_POW + 1) as u32) - FIRST_FRAGMENT_CAPACITY
}

const fn capacities_len() -> usize {
    #[cfg(target_pointer_width = "32")]
    return 30;

    #[cfg(target_pointer_width = "64")]
    return 33;
}

pub(super) const CUMULATIVE_CAPACITIES: [usize; capacities_len()] = [
    0,
    cumulative_capacity(0),
    cumulative_capacity(1),
    cumulative_capacity(2),
    cumulative_capacity(3),
    cumulative_capacity(4),
    cumulative_capacity(5),
    cumulative_capacity(6),
    cumulative_capacity(7),
    cumulative_capacity(8),
    cumulative_capacity(9),
    cumulative_capacity(10),
    cumulative_capacity(11),
    cumulative_capacity(12),
    cumulative_capacity(13),
    cumulative_capacity(14),
    cumulative_capacity(15),
    cumulative_capacity(16),
    cumulative_capacity(17),
    cumulative_capacity(18),
    cumulative_capacity(19),
    cumulative_capacity(20),
    cumulative_capacity(21),
    cumulative_capacity(22),
    cumulative_capacity(23),
    cumulative_capacity(24),
    cumulative_capacity(25),
    cumulative_capacity(26),
    cumulative_capacity(27),
    cumulative_capacity(28),
    #[cfg(target_pointer_width = "64")]
    cumulative_capacity(29),
    #[cfg(target_pointer_width = "64")]
    cumulative_capacity(30),
    #[cfg(target_pointer_width = "64")]
    cumulative_capacity(31),
];
```

**Comment by orxfun** [comment]
> I tried the fix and it gets the project to compile but it seems there's an immediate runtime overflow in
> 
> ```
>     #[inline(always)]
>     fn new_fragment_capacity_from(
>         &self,
>         fragment_capacities: impl ExactSizeIterator<Item = usize>,
>     ) -> usize {
>         fragment_capacities.last().map(|x| x * 2).unwrap_or(4)
>     }
> ```
> 
> In `orx-split-vec-69c925888591bba4/24b4fda/src/growth/doubling/doubling_growth.rs:68:44`:

Hi @MichaReiser . Thanks for reporting the issue! Is it possible to provide a little more details? Specifically, do you observe the issue immediataly or when the vector grows to a certain capacity? As there are a couple of ways to approach to this, it would be very helpful to know.

**Comment by MichaReiser** [comment]
I haven't looked into that yet. It happens immediately when the application starts and at best after a few insertions. But I would have to add debug statements in the wasm build to see how many items get pushed.

**Comment by orxfun** [comment]
> I haven't looked into that yet. It happens immediately when the application starts and at best after a few insertions. But I would have to add debug statements in the wasm build to see how many items get pushed.

It already gives me the idea, thanks! Only trouble on my side is that currently I am not on my dev environment, still on vacation. I will be able to dive into the issue in one week. Lastly, could you share your build target please.

**Comment by orxfun** [comment]
Merging and closing this PR. There will be an additional fix for different growth types and corresponding tests will be added. @MichaReiser, I will let you know once the complete fix is ready. Then, it would be great if you could let me know if you still experience the issue.

**Pull request merged**
